#!/bin/sh
#
# @name Aerial Manipulator Tilted Hex
#
# @type Hexarotor x
# @class Copter
#
# @maintainer LeCAR Lab <lecar-lab@cmu.edu>
#

. ${R}etc/init.d/rc.mc_defaults

# MAV_TYPE_HEXAROTOR. CA_AIRFRAME=0 selects the custom rotor geometry below;
# CA_METHOD=0 is PX4's native pseudo-inverse allocation plus final clipping.
param set-default MAV_TYPE 13
param set-default CA_AIRFRAME 0
param set-default CA_METHOD 0

# Flight-proven physical output order:
#   1 mid-right, 2 mid-left, 3 front-left,
#   4 rear-right, 5 front-right, 6 rear-left.
# Positions and axes are normalized. Ct=1 and |Km|=0.05 are allocator
# normalization values, not measured propulsion coefficients.
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR0_AX 0.5
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -0.866025
param set-default CA_ROTOR0_CT 1
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR1_AX 0.5
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -0.866025
param set-default CA_ROTOR1_CT 1
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.866025
param set-default CA_ROTOR2_PY -0.5
param set-default CA_ROTOR2_AX -0.25
param set-default CA_ROTOR2_AY -0.4330125
param set-default CA_ROTOR2_AZ -0.866025
param set-default CA_ROTOR2_CT 1
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.866025
param set-default CA_ROTOR3_PY 0.5
param set-default CA_ROTOR3_AX -0.25
param set-default CA_ROTOR3_AY -0.4330125
param set-default CA_ROTOR3_AZ -0.866025
param set-default CA_ROTOR3_CT 1
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX 0.866025
param set-default CA_ROTOR4_PY 0.5
param set-default CA_ROTOR4_AX -0.25
param set-default CA_ROTOR4_AY 0.4330125
param set-default CA_ROTOR4_AZ -0.866025
param set-default CA_ROTOR4_CT 1
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX -0.866025
param set-default CA_ROTOR5_PY -0.5
param set-default CA_ROTOR5_AX -0.25
param set-default CA_ROTOR5_AY 0.4330125
param set-default CA_ROTOR5_AZ -0.866025
param set-default CA_ROTOR5_CT 1
param set-default CA_ROTOR5_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

# Preserve the installed PWM ESC electrical contract from the accepted v1.10
# parameter snapshot. These values still require a props-removed bench check.
param set-default PWM_MAIN_DIS1 900
param set-default PWM_MAIN_DIS2 900
param set-default PWM_MAIN_DIS3 900
param set-default PWM_MAIN_DIS4 900
param set-default PWM_MAIN_DIS5 900
param set-default PWM_MAIN_DIS6 900
param set-default PWM_MAIN_MIN1 1075
param set-default PWM_MAIN_MIN2 1075
param set-default PWM_MAIN_MIN3 1075
param set-default PWM_MAIN_MIN4 1075
param set-default PWM_MAIN_MIN5 1075
param set-default PWM_MAIN_MIN6 1075
param set-default PWM_MAIN_MAX1 1950
param set-default PWM_MAIN_MAX2 1950
param set-default PWM_MAIN_MAX3 1950
param set-default PWM_MAIN_MAX4 1950
param set-default PWM_MAIN_MAX5 1950
param set-default PWM_MAIN_MAX6 1950

# TELEM1 is the dedicated candidate uXRCE-DDS link to the SNUC. Do not place
# MAVLink on this byte stream. USB CDC retains QGC/MAVLink and recovery access;
# TELEM2 remains available for an independently configured MAVLink link.
param set-default MAV_0_CONFIG 0
param set-default SER_TEL1_BAUD 921600
param set-default UXRCE_DDS_CFG 101
